name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  build-and-convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Render and Convert Quarto Documents
      run: |
        OIFS="$IFS"
        IFS=$'\n'
        for file in $(find . -name "*.qmd"); do
          dir_name=$(dirname "$file")
          sudo chmod ugo+rwx "$dir_name"
          mkdir -p "$dir_name/slides"
          base_name="${file%.qmd}"
          pdf_path="$dir_name/slides/$(basename "$base_name").pdf"

          quarto render "$file"
          docker run --rm -t -v ${{ github.workspace }}:/workspace astefanutti/decktape "$base_name.html" "$pdf_path"

          git add "$pdf_path"
        done
        IFS="$OIFS"
        
    - name: Commit and push PDFs
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Update PDFs"
        git push