name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  build-and-convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
        
    - name: Render to HTML and convert to PDF
      run: |
        for file in $(find . -name '*.qmd' -print); do
          echo "Processing $file"
          quarto render "$file" --to html
          ls
        done
      