name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  build-and-convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true
        
    - name: Render to HTML and convert to PDF
      run: |
        quarto render '0. oficina-zero/wsl.qmd'
        sudo chmod ugo+rwx '0. oficina-zero'
        docker run --rm -t -v ${{ github.workspace }}:/slides astefanutti/decktape '0. oficina-zero/wsl.html' '0. oficina-zero/wsl.pdf'
        git add '0. oficina-zero/wsl.pdf'
      
    - name: Commit and push PDFs
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Add generated PDFs"
        git push